use_frameworks!
#enable_bitcode_for_prebuilt_frameworks!
target 'OMGJanusWebRTC_Example' do
  pod 'OMGJanusWebRTC', :path => '../'

  target 'OMGJanusWebRTC_Tests' do
    inherit! :search_paths

    
  end
end
